### ISSUE TITLE
Rocm overlay and Tensorflow to compile with export TF_NEED_ROCM=1

### ISSUE THREAD

**Issue by perestoronin** [justxi/rocm#153]
I not happy use Rocm overlay to compile Tensorflow with flag export TF_NEED_ROCM=1.

Please help me!

For example I used https://github.com/perestoronin/ml/blob/master/sci-libs/tensorflow/tensorflow-2.2.0.ebuild and failed with errors:

`INFO: Call stack for the definition of repository 'local_config_rocm' which is a rocm_configure (rule definition at /var/tmp/portage/sci-libs/tensorflow-2.2.0/work/tensorflow-2.2.0-python3_8/third_party/gpus/rocm_configure.bzl:867:18):
 - /var/tmp/portage/sci-libs/tensorflow-2.2.0/work/tensorflow-2.2.0-python3_8/tensorflow/workspace.bzl:98:5
 - /var/tmp/portage/sci-libs/tensorflow-2.2.0/work/tensorflow-2.2.0-python3_8/WORKSPACE:28:1
ERROR: An error occurred during the fetch of repository 'local_config_rocm':
   Traceback (most recent call last):
	File "/var/tmp/portage/sci-libs/tensorflow-2.2.0/work/tensorflow-2.2.0-python3_8/third_party/gpus/rocm_configure.bzl", line 846
		_create_local_rocm_repository(<1 more arguments>)
	File "/var/tmp/portage/sci-libs/tensorflow-2.2.0/work/tensorflow-2.2.0-python3_8/third_party/gpus/rocm_configure.bzl", line 614, in _create_local_rocm_repository
		make_copy_dir_rule(<4 more arguments>)
	File "/var/tmp/portage/sci-libs/tensorflow-2.2.0/work/tensorflow-2.2.0-python3_8/third_party/gpus/cuda_configure.bzl", line 818, in make_copy_dir_rule
		read_dir(repository_ctx, <1 more arguments>)
	File "/var/tmp/portage/sci-libs/tensorflow-2.2.0/work/tensorflow-2.2.0-python3_8/third_party/remote_config/common.bzl", line 101, in read_dir
		execute(repository_ctx, <2 more arguments>)
	File "/var/tmp/portage/sci-libs/tensorflow-2.2.0/work/tensorflow-2.2.0-python3_8/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed
`

**Comment by justxi** [comment]
What is "local_config_rocm"?
It seems like a problem fetching somethng(?). 
Can you provide the whole build.log?
Did you try to build tensorflow without the ebuild?

**Comment by perestoronin** [comment]
About local_config_rocm few info on https://chromium.googlesource.com/external/github.com/tensorflow/tensorflow/+/refs/heads/master/tensorflow/tensorflow.bzl

(build.log}[https://gist.github.com/raw/e08bc604a2c42ede8edb6cde567375bd]

No, I don't try compile without ebuild.

**Comment by justxi** [comment]
I think you should run all steps from your ebuild without the ebuld. My guess is, that something can not be fetched  / downloaded because the ebuild environments restricts this.

**Comment by justxi** [comment]
Any progress?

**Comment by justxi** [comment]
I think further disussion could be done here -> https://github.com/justxi/rocm/issues/133
