### ISSUE TITLE
Broken for me

### ISSUE THREAD

**Issue by Lucretia** [justxi/rocm#89]
Hi, in the last few days, something has changed and broken it for me. I've not changed kernel, I have done an upgrade which was kind of huge, but mainly kde stuff. If I install the latest 2.7.0/2.7.9999 stuff, the versions I posted before, clinfo segfaults again (the mec firmware from the ROCm issues is still at the correct version and, like I said, kernel hasn't changed).

I started a new branch here to try to get things working again, but it's just not working, not sure why.

```
$ rocminfo 
ROCk module is loaded
laguest is member of video group
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  0.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*** Done ***

I managed to roll back a few commits on rocr-runtime, but the best I get is this:

$ clinfo 
Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.0 AMD-APP.internal (2949.0)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_object_metadata cl_amd_event_callback 
  Platform Max metadata object keys (AMD)         8
  Platform Extensions function suffix             AMD

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 0

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  AMD Accelerated Parallel Processing
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   
  clCreateContext(NULL, ...) [default]            No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No devices found in platform

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.12
  ICD loader Profile                              OpenCL 2.2
'''

I have the GPU nodes in the topology in /sys showing.

**Comment by justxi** [comment]
I had the same problem using the *.9999 ebuilds. Don´t you get a stable system, using only 2.7.0 ebuilds?

**Comment by justxi** [comment]
Currently we are working on the ebuilds for 2.8, maybe you want to test this instead of spending time to get 2.7 working?

**Comment by Lucretia** [comment]
I'm pretty sure the basic 2.7.0 ebuilds just gave me segfaults.

I've not had a chance to try 2.8.0 yet, but I will in the next few days.

**Comment by justxi** [comment]
Which one give you a segfault?
An ebuild from this repository or from Gentoo portage?
If you mixed them, I would suggest to try ROCm 2.8, because all ebuilds in Gentoo portage are updated now and the others here too.

**Comment by justxi** [comment]
Maybe your problem is related to this: https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/issues/44

**Comment by Lucretia** [comment]
could very well be, I have the same issues as he does.

**Comment by Lucretia** [comment]
Ok, just finished upograde to 2.8.0.

```
# rocminfo 
ROCk module is loaded
laguest is member of video group
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD FX(tm)-8350 Eight-Core Processor
  Marketing Name:          AMD FX(tm)-8350 Eight-Core Processor
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      16384(0x4000) KB                   
  Chip ID:                 0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   4000                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            8                                  
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    32836652(0x1f50c2c) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    32836652(0x1f50c2c) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        TRUE                               
  ISA Info:                
    N/A                      
*******                  
Agent 2                  
*******                  
  Name:                    gfx701                             
  Marketing Name:          Hawaii PRO [Radeon R9 290/390]     
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          4096(0x1000)                       
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
  Chip ID:                 26545(0x67b1)                      
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1040                               
  BDFID:                   256                                
  Internal Node ID:        1                                  
  Compute Unit:            40                                 
  SIMDs per CU:            4                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    8388608(0x800000) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Acessible by all:        FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx701          
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                FALSE                              
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***
```

Running clinfo gives me an error in the dmesg log again:

```
[Oct 2 15:58] clinfo[18827]: segfault at 1000 ip 00007fd9f372b26a sp 00007ffe8d745420 error 6 in libhsa-runtime64.so.1.1.9[7fd9f370c000+cf000]
[  +0.000005] Code: ff ff ff 48 8b 85 58 ff ff ff 48 8b 80 b8 03 00 00 48 8b 95 78 ff ff ff 48 c1 e2 03 48 01 c2 48 8b 85 68 ff ff ff 48 8b 40 18 <48> 89 02 c6 45 b0 01 90 bb 00 00 00 00 0f b6 45 b0 83 f0 01 84 c0
```

The backtrace on clinfo is:

```
Thread 1 "clinfo" received signal SIGSEGV, Segmentation fault.
0x00007ffff7ab526a in amd::GpuAgent::QueueCreate(unsigned long, unsigned int, void (*)(hsa_status_t, hsa_queue_s*, void*), void*, unsigned int, unsigned int, core::Queue**) () from /usr/lib64/libhsa-runtime64.so.1
(gdb) bt
#0  0x00007ffff7ab526a in amd::GpuAgent::QueueCreate(unsigned long, unsigned int, void (*)(hsa_status_t, hsa_queue_s*, void*), void*, unsigned int, unsigned int, core::Queue**) () from /usr/lib64/libhsa-runtime64.so.1
#1  0x00007ffff7ab3891 in amd::GpuAgent::CreateInterceptibleQueue() () from /usr/lib64/libhsa-runtime64.so.1
#2  0x00007ffff7ab3ae0 in amd::GpuAgent::InitDma()::{lambda()#1}::operator()() const () from /usr/lib64/libhsa-runtime64.so.1
#3  0x00007ffff7ab6de7 in std::_Function_handler<core::Queue* (), amd::GpuAgent::InitDma()::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from /usr/lib64/libhsa-runtime64.so.1
#4  0x00007ffff7abc930 in std::function<core::Queue* ()>::operator()() const () from /usr/lib64/libhsa-runtime64.so.1
#5  0x00007ffff7abbbd7 in lazy_ptr<core::Queue>::make_body(bool) const () from /usr/lib64/libhsa-runtime64.so.1
#6  0x00007ffff7aba14c in lazy_ptr<core::Queue>::operator->() const () from /usr/lib64/libhsa-runtime64.so.1
#7  0x00007ffff7ab621f in amd::GpuAgent::InvalidateCodeCaches() () from /usr/lib64/libhsa-runtime64.so.1
#8  0x00007ffff7ac518b in amd::LoaderContext::SegmentAlloc(amdgpu_hsa_elf_segment_t, hsa_agent_s, unsigned long, unsigned long, bool) () from /usr/lib64/libhsa-runtime64.so.1
#9  0x00007ffff7b26e9f in amd::hsa::loader::ExecutableImpl::LoadSegmentsV2(hsa_agent_s, amd::hsa::code::AmdHsaCode const*) () from /usr/lib64/libhsa-runtime64.so.1
#10 0x00007ffff7b26d0d in amd::hsa::loader::ExecutableImpl::LoadSegments(hsa_agent_s, amd::hsa::code::AmdHsaCode const*, unsigned int) () from /usr/lib64/libhsa-runtime64.so.1
#11 0x00007ffff7b2679a in amd::hsa::loader::ExecutableImpl::LoadCodeObject(hsa_agent_s, hsa_code_object_s, unsigned long, char const*, hsa_loaded_code_object_s*) () from /usr/lib64/libhsa-runtime64.so.1
#12 0x00007ffff7b2596d in amd::hsa::loader::ExecutableImpl::LoadCodeObject(hsa_agent_s, hsa_code_object_s, char const*, hsa_loaded_code_object_s*) () from /usr/lib64/libhsa-runtime64.so.1
#13 0x00007ffff7ae595a in HSA::hsa_executable_load_agent_code_object(hsa_executable_s, hsa_agent_s, hsa_code_object_reader_s, char const*, hsa_loaded_code_object_s*) () from /usr/lib64/libhsa-runtime64.so.1
#14 0x00007ffff7b21138 in hsa_executable_load_agent_code_object () from /usr/lib64/libhsa-runtime64.so.1
#15 0x00007ffff7c987d8 in ?? () from /usr/lib64/libamdocl64.so
#16 0x00007ffff7c73196 in ?? () from /usr/lib64/libamdocl64.so
#17 0x00007ffff7c6f3ef in ?? () from /usr/lib64/libamdocl64.so
#18 0x00007ffff7c8173f in ?? () from /usr/lib64/libamdocl64.so
#19 0x00007ffff7c5c24a in ?? () from /usr/lib64/libamdocl64.so
#20 0x00007ffff7c9efce in ?? () from /usr/lib64/libamdocl64.so
#21 0x00007ffff7ca011d in ?? () from /usr/lib64/libamdocl64.so
#22 0x00007ffff7c59831 in ?? () from /usr/lib64/libamdocl64.so
#23 0x00007ffff7c7b086 in ?? () from /usr/lib64/libamdocl64.so
#24 0x00007ffff7cd0c55 in ?? () from /usr/lib64/libamdocl64.so
#25 0x00007ffff7d39bdf in __pthread_once_slow () from /lib64/libpthread.so.0
#26 0x00007ffff7cd0d6c in clIcdGetPlatformIDsKHR () from /usr/lib64/libamdocl64.so
#27 0x00007ffff7f2415d in ?? () from /usr/lib64/OpenCL/vendors/ocl-icd/libOpenCL.so.1
#28 0x00007ffff7d39bdf in __pthread_once_slow () from /lib64/libpthread.so.0
#29 0x00007ffff7f23428 in ?? () from /usr/lib64/OpenCL/vendors/ocl-icd/libOpenCL.so.1
#30 0x00007ffff7f26234 in clGetPlatformIDs () from /usr/lib64/OpenCL/vendors/ocl-icd/libOpenCL.so.1
#31 0x000055555555a420 in main (argc=<optimized out>, argv=<optimized out>) at src/clinfo.c:3190
```

The MEC firmware hasn't changed as @fxkamd mentioned in the previous issues:

```
# cat /sys/kernel/debug/dri/0/amdgpu_firmware_info
VCE feature version: 0, firmware version: 0x320a0200
UVD feature version: 0, firmware version: 0x01400900
MC feature version: 0, firmware version: 0x00c79110
ME feature version: 29, firmware version: 0x000000bb
PFP feature version: 29, firmware version: 0x000000e5
CE feature version: 29, firmware version: 0x0000007a
RLC feature version: 1, firmware version: 0x00000011
RLC SRLC feature version: 0, firmware version: 0x00000000
RLC SRLG feature version: 0, firmware version: 0x00000000
RLC SRLS feature version: 0, firmware version: 0x00000000
MEC feature version: 24, firmware version: 0x000001a7
SOS feature version: 0, firmware version: 0x00000000
ASD feature version: 0, firmware version: 0x00000000
TA XGMI feature version: 0, firmware version: 0x00000000
TA RAS feature version: 0, firmware version: 0x00000000
SMC feature version: 0, firmware version: 0x000f0600
SDMA0 feature version: 9, firmware version: 0x0000004c
SDMA1 feature version: 0, firmware version: 0x0000004c
VCN feature version: 0, firmware version: 0x00000000
DMCU feature version: 0, firmware version: 0x00000000
VBIOS version: 113-2E32430-X4J
```

As mentioned in the link above:

```
# ls -la /sys/devices/system/node/node*
total 0
drwxr-xr-x 4 root root    0 Oct  2 15:50 .
drwxr-xr-x 4 root root    0 Oct  2 15:50 ..
--w------- 1 root root 4096 Oct  2 16:00 compact
lrwxrwxrwx 1 root root    0 Oct  2 15:50 cpu0 -> ../../cpu/cpu0
lrwxrwxrwx 1 root root    0 Oct  2 15:50 cpu1 -> ../../cpu/cpu1
lrwxrwxrwx 1 root root    0 Oct  2 15:50 cpu2 -> ../../cpu/cpu2
lrwxrwxrwx 1 root root    0 Oct  2 15:50 cpu3 -> ../../cpu/cpu3
lrwxrwxrwx 1 root root    0 Oct  2 15:50 cpu4 -> ../../cpu/cpu4
lrwxrwxrwx 1 root root    0 Oct  2 15:50 cpu5 -> ../../cpu/cpu5
lrwxrwxrwx 1 root root    0 Oct  2 15:50 cpu6 -> ../../cpu/cpu6
lrwxrwxrwx 1 root root    0 Oct  2 15:50 cpu7 -> ../../cpu/cpu7
-r--r--r-- 1 root root 4096 Oct  2 16:00 cpulist
-r--r--r-- 1 root root 4096 Oct  2 16:00 cpumap
-r--r--r-- 1 root root 4096 Oct  2 16:00 distance
drwxr-xr-x 3 root root    0 Oct  2 16:00 hugepages
-r--r--r-- 1 root root 4096 Oct  2 15:50 meminfo
-r--r--r-- 1 root root 4096 Oct  2 16:00 numastat
drwxr-xr-x 2 root root    0 Oct  2 16:00 power
lrwxrwxrwx 1 root root    0 Oct  2 16:00 subsystem -> ../../../../bus/node
-rw-r--r-- 1 root root 4096 Oct  2 16:00 uevent
-r--r--r-- 1 root root 4096 Oct  2 16:00 vmstat
# ls -ld /sys/devices/system/cpu/cpu*
drwxr-xr-x  8 root root 0 Oct  2 15:37 /sys/devices/system/cpu/cpu0
drwxr-xr-x  8 root root 0 Oct  2 15:37 /sys/devices/system/cpu/cpu1
drwxr-xr-x  8 root root 0 Oct  2 15:37 /sys/devices/system/cpu/cpu2
drwxr-xr-x  8 root root 0 Oct  2 15:37 /sys/devices/system/cpu/cpu3
drwxr-xr-x  8 root root 0 Oct  2 15:37 /sys/devices/system/cpu/cpu4
drwxr-xr-x  8 root root 0 Oct  2 15:37 /sys/devices/system/cpu/cpu5
drwxr-xr-x  8 root root 0 Oct  2 15:37 /sys/devices/system/cpu/cpu6
drwxr-xr-x  8 root root 0 Oct  2 15:37 /sys/devices/system/cpu/cpu7
drwxr-xr-x 10 root root 0 Oct  2 15:37 /sys/devices/system/cpu/cpufreq
drwxr-xr-x  2 root root 0 Oct  2 16:00 /sys/devices/system/cpu/cpuidle
```

**Comment by justxi** [comment]
I think here is the same problem: 

https://github.com/RadeonOpenCompute/ROCR-Runtime/issues/68#issuecomment-537491922

**Comment by Lucretia** [comment]
Yes, I just applied that doorbell patch by hand and re-compiled rocr-runtime, clinfo now works again. Might be worth adding the patch into the 2.8.0 ebuild.

**Comment by justxi** [comment]
I think you should submit a bug report at https://bugs.gentoo.org .. because this is related to ebuilds which are already in portage.

**Comment by Lucretia** [comment]
https://bugs.gentoo.org/696108

**Comment by Lucretia** [comment]
There's still an issue. On kernel 5.3.2-gentoo, running clinfo, dumps out to dmesg the following oops:

```
[Oct 3 14:10] ------------[ cut here ]------------
[  +0.000003] FW bug: No PASID in KFD interrupt
[  +0.000176] WARNING: CPU: 7 PID: 0 at drivers/gpu/drm/amd/amdgpu/../amdkfd/cik_event_interrupt.c:70 cik_event_interrupt_isr+0xee/0x130 [amdgpu]
[  +0.000000] Modules linked in: ebtable_filter ebtables ip6table_filter rfcomm nfsd nf_conntrack_netlink nfnetlink xfrm_user xfrm_algo br_netfilter cmac bnep snd_seq_dummy snd_seq_oss snd_pcm_oss snd_mixer_oss 8021q binfmt_misc ip6table_nat ip6_tables twofish_avx_x86_64 twofish_x86_64_3way twofish_x86_64 twofish_common serpent_avx_x86_64 serpent_generic cast6_avx_x86_64 cast6_generic cast5_avx_x86_64 cast5_generic cast_common sha512_ssse3 sha256_ssse3 sha1_ssse3 hfsplus hfs cpufreq_userspace cpufreq_powersave cpufreq_conservative cpufreq_ondemand uinput tun bridge stp llc ipv6 crc_ccitt 9pnet_virtio 9p 9pnet vfio_pci kvm_amd vfio_virqfd kvm irqbypass snd_seq_midi snd_seq_midi_event crct10dif_pclmul snd_seq crc32_pclmul msr cpuid aesni_intel crypto_simd cryptd glue_helper pcspkr fam15h_power k10temp joydev input_leds hid_uclogic btusb btrtl btbcm btintel bluetooth ecdh_generic ecc it87 hwmon_vid hid_steam rfkill snd_hda_codec_realtek snd_usb_audio snd_usbmidi_lib snd_rawmidi r8152
[  +0.000023]  snd_seq_device uas mc snd_hda_codec_generic amdgpu snd_hda_intel i2c_piix4 snd_hda_codec amd_iommu_v2 snd_hwdep gpu_sched snd_hda_core snd_pcm snd_timer snd ttm acpi_cpufreq button virtio_pci virtio_scsi virtio_blk virtio_console virtio_balloon aes_x86_64 sha512_generic libiscsi scsi_transport_iscsi vxlan ip6_udp_tunnel udp_tunnel macvlan virtio_net net_failover failover virtio_ring virtio pcnet32 fuse nfs lockd grace sunrpc jfs multipath linear raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx raid1 raid0 dm_snapshot dm_bufio dm_crypt dm_mirror dm_region_hash dm_log dm_mod dax hid_sony ff_memless hid_logitech hid_a4tech sl811_hcd uhci_hcd aic94xx libsas lpfc crc_t10dif qla2xxx megaraid_sas megaraid_mbox megaraid_mm megaraid aacraid sx8 3w_9xxx 3w_xxxx mptsas scsi_transport_sas mptfc scsi_transport_fc mptspi mptscsih mptbase atp870u dc395x qla1280 imm parport dmx3191d sym53c8xx led_class gdth initio BusLogic arcmsr aic7xxx aic79xx scsi_transport_spi sg
[  +0.000033]  pdc_adma sata_inic162x sata_mv ata_piix sata_qstor sata_vsc sata_uli sata_sis sata_sx4 sata_nv sata_via sata_svw sata_sil24 sata_sil sata_promise pata_sl82c105 pata_via pata_jmicron pata_marvell pata_sis pata_netcell pata_pdc202xx_old pata_triflex pata_atiixp pata_opti pata_amd pata_ali pata_it8213 pata_pcmcia pcmcia pcmcia_core pata_ns87415 pata_ns87410 pata_serverworks pata_artop pata_it821x pata_optidma pata_hpt3x2n pata_hpt3x3 pata_hpt37x pata_hpt366 pata_cmd64x pata_efar pata_rz1000 pata_sil680 pata_radisys pata_pdc2027x pata_mpiix usb_storage mii crct10dif_common r8169 libphy ahci libahci libata
[  +0.000019] CPU: 7 PID: 0 Comm: swapper/7 Not tainted 5.3.2-gentoo #1
[  +0.000001] Hardware name: To be filled by O.E.M. To be filled by O.E.M./M5A99FX PRO R2.0, BIOS 2301 01/06/2014
[  +0.000032] RIP: 0010:cik_event_interrupt_isr+0xee/0x130 [amdgpu]
[  +0.000002] Code: 94 00 00 00 72 5a c1 e9 10 75 28 44 8a 25 be 84 21 00 45 84 e4 75 17 48 c7 c7 d6 06 e0 c0 c6 05 ab 84 21 00 01 e8 0d c9 3d c0 <0f> 0b eb 32 45 31 e4 eb 2d 8d 88 4b ff ff ff b0 01 83 f9 3a 77 13
[  +0.000001] RSP: 0018:ffff9193801f4dd8 EFLAGS: 00010086
[  +0.000001] RAX: 0000000000000000 RBX: ffff8abd7380c800 RCX: 0000000000000000
[  +0.000001] RDX: 0000000000010003 RSI: ffffffff82944ce1 RDI: 00000000ffffffff
[  +0.000000] RBP: ffff9193801f4df8 R08: 00000071478a1039 R09: 0000000000000021
[  +0.000001] R10: 0000000000000000 R11: 0000000000000044 R12: 0000000000000000
[  +0.000001] R13: ffff8abd7380c9e0 R14: ffff9193801f4e10 R15: 0000000000000000
[  +0.000001] FS:  0000000000000000(0000) GS:ffff8abe7ebc0000(0000) knlGS:0000000000000000
[  +0.000001] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  +0.000000] CR2: 00007fc05718ea30 CR3: 00000005efd67000 CR4: 00000000000406e0
[  +0.000012] Call Trace:
[  +0.000002]  <IRQ>
[  +0.000031]  kgd2kfd_interrupt+0x9b/0xfc [amdgpu]
[  +0.000037]  amdgpu_irq_dispatch+0x17b/0x199 [amdgpu]
[  +0.000004]  ? rcu_accelerate_cbs+0x49/0x132
[  +0.000030]  amdgpu_ih_process+0x85/0xe0 [amdgpu]
[  +0.000031]  amdgpu_irq_handler+0x16/0x34 [amdgpu]
[  +0.000002]  __handle_irq_event_percpu+0x90/0x17e
[  +0.000002]  handle_irq_event_percpu+0x2c/0x6f
[  +0.000001]  handle_irq_event+0x2f/0x4c
[  +0.000002]  handle_edge_irq+0x105/0x122
[  +0.000002]  handle_irq+0x19/0x1c
[  +0.000003]  do_IRQ+0x62/0x108
[  +0.000002]  common_interrupt+0xf/0xf
[  +0.000001]  </IRQ>
[  +0.000002] RIP: 0010:cpuidle_enter_state+0x227/0x333
[  +0.000001] Code: 7e 75 05 e8 fe 6b 8c ff 31 ff e8 2a a9 93 ff 45 84 ed 74 12 9c 58 0f ba e0 09 73 03 0f 0b fa 31 ff e8 0b e3 97 ff fb 45 85 e4 <0f> 88 ed 00 00 00 49 63 cc be ff ff ff 7f 48 ba ff ff ff ff f3 01
[  +0.000001] RSP: 0018:ffff9193800b7e78 EFLAGS: 00000202 ORIG_RAX: ffffffffffffffd9
[  +0.000002] RAX: ffff8abe7ebc0000 RBX: ffff8abe7ab35800 RCX: 000000000000001f
[  +0.000000] RDX: 0000000000000000 RSI: 000000001fe466fc RDI: 0000000000000000
[  +0.000001] RBP: ffffffff824d29e0 R08: 000000714789a88d R09: 00000000007d9db4
[  +0.000001] R10: 071c71c71c71c71c R11: 0000000000000020 R12: 0000000000000002
[  +0.000001] R13: 0000000000000000 R14: ffffffff824d2ab8 R15: 0000000000000000
[  +0.000002]  ? cpuidle_enter_state+0x20c/0x333
[  +0.000001]  ? menu_select+0x423/0x4aa
[  +0.000002]  cpuidle_enter+0x25/0x31
[  +0.000002]  do_idle+0x17a/0x1ed
[  +0.000002]  cpu_startup_entry+0x18/0x1a
[  +0.000002]  start_secondary+0x151/0x16c
[  +0.000002]  secondary_startup_64+0xa4/0xb0
[  +0.000001] ---[ end trace 3d24447d7036f6f6 ]---
```

**Comment by justxi** [comment]
If it is related to a specific kernel version, I think this sould be reported to AMD.

**Comment by justxi** [comment]
I just tried ROCm 2.9 on kernel 5.3.1-gentoo and all (clinfo, rocminfo, rocm-smi) seem to work fine.

**Comment by justxi** [comment]
I close this due to inactivity.
